# Generated by Django 2.0.5 on 2018-05-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
